version: '2'

services:
    device-kiwi-prugw:
        image: chalmersrevere/opendlv-device-kiwi-prugw:v0.0.3
        network_mode: "host"
        privileged: true
        restart: always
        volumes:
            - /sys/:/sys/
        command: "/usr/bin/opendlv-device-kiwi-prugw --cid=${CID} \
                --names=${NAMES} --types=${TYPES} --channels=${CHANNELS} \
                --offsets=${OFFSETS} --maxvals=${MAXVALS} \
                --angleconversion=${ANGLECONVERSION} --verbose=0"
    device-ultrasonic-srf08-front:
        image: chalmersrevere/opendlv-device-ultrasonic-srf08-armhf:v0.0.4
        network_mode: "host"
        privileged: true
        restart: always
        volumes:
          - /dev/i2c-1:/dev/i2c-1
        command: "/usr/bin/opendlv-device-ultrasonic-srf08 --dev=/dev/i2c-1 --bus-address=112 --cid=${CID} --freq=5 --id=0"
    
    device-ultrasonic-srf08-rear:
        image: chalmersrevere/opendlv-device-ultrasonic-srf08-armhf:v0.0.4
        network_mode: "host"
        privileged: true
        restart: always
        volumes:
          - /dev/i2c-1:/dev/i2c-1
        command: "/usr/bin/opendlv-device-ultrasonic-srf08 --dev=/dev/i2c-1 --bus-address=113 --cid=${CID} --freq=5 --id=1"
    
    device-adc-bbblue-left:
        image: chalmersrevere/opendlv-device-adc-bbblue-armhf:v0.0.4
        network_mode: "host"
        privileged: true
        restart: always
        volumes:
          - /dev/mem:/dev/mem
        command: "/usr/bin/opendlv-device-adc-bbblue --cid=${CID} --freq=5 --channel=4 --id=0"
    
    device-adc-bbblue-right:
        image: chalmersrevere/opendlv-device-adc-bbblue-armhf:v0.0.4
        network_mode: "host"
        privileged: true
        restart: always
        volumes:
          - /dev/mem:/dev/mem
        command: "/usr/bin/opendlv-device-adc-bbblue --cid=${CID} --freq=5 --channel=3 --id=1"

    # viewer:
    #     image: chalmersrevere/opendlv-signal-viewer-multi:v0.0.2
    #     network_mode: "host"
    #     restart: always
    #     ports:
    #         - "8080:8080"
    #     command: "--cid=${CID}"