version: '2'

services:
    device-kiwi-prugw:
        image: openkorp/opendlv-device-kiwi-prugw-multi:latest
        network_mode: "host"
        privileged: true
        restart: always
        volumes:
            - /sys/:/sys/
        command: "/usr/bin/opendlv-device-kiwi-prugw --cid=${CID} \
                --names=${NAMES} --types=${TYPES} --channels=${CHANNELS} \
                --offsets=${OFFSETS} --maxvals=${MAXVALS} \
                --angleconversion=${ANGLECONVERSION} --verbose=0"

    # viewer:
    #     image: chalmersrevere/opendlv-signal-viewer-multi:v0.0.2
    #     network_mode: "host"
    #     restart: always
    #     ports:
    #         - "8080:8080"
    #     command: "--cid=${CID}"